#!/bin/bash

set -eu

declare -i  EXPECTED_TTL=0
declare -r  UPDATE_CMD=/usr/bin/jupiter-controller-update
declare -ar CHECK_CMD=($UPDATE_CMD --check)
shopt -s extglob

firmware_update_required ()
{
    local -i rc=1
    local status=
    while read -r status
    do
        echo "$status"
        case $status in
            (time_estimate=+([0-9])) EXPECTED_TTL=${status#*=} ;;
            (needs_update=[1-9]*)    rc=0 ;;
        esac
    done < <("${CHECK_CMD[@]}" | grep -iE '^[a-z]')

    return ${rc}
}

if firmware_update_required
then
    # shellcheck disable=SC2086
    /usr/bin/plymouth-wrap ${EXPECTED_TTL} firmware-update "${UPDATE_CMD}"
else
    exit 0
fi
