#!/bin/bash

set -eu

declare -r  SIMULATE=/etc/.simulate-firmware-update
declare -r  VERBOSE=/etc/.verbose-firmware-update
declare -i  EXPECTED_TTL=0
declare -r  UPDATE_CMD=/usr/bin/jupiter-controller-update
declare -r  FAKE_CMD=/usr/lib/hwsupport/jupiter-controller-fake-update
declare -ar CHECK_CMD=($UPDATE_CMD --check)
declare -a  EXTRA_WRAP_ARGS=()
declare     FAKE_TTL=
shopt -s extglob

firmware_update_required ()
{
    local -i check_status=0
    local status=
    local check_output=

    check_output=$("${CHECK_CMD[@]}") || check_status=$?

    while read -r status
    do
        echo "$status"
        case $status in
            (time_estimate=+([0-9])) EXPECTED_TTL=${status#*=} ;;
        esac
    done <<< "$check_output"

    # jupiter-controller-update --check exit code
    # exit 0 - firmware is up to date
    # exit 7 - firmware update needed
    # anything else - the check itself failed (real error)
    case $check_status in
        (0) return 1 ;;
        (7) return 0 ;;
        (*) echo "!! '${CHECK_CMD[*]}' exited ${check_status}" >&2
            exit 1 ;;
    esac
}

fake_update_requested ()
{
    if [ -e ${SIMULATE} ]
    then
        if [ -s ${SIMULATE} ]
        then
            read -r FAKE_TTL < <(head -n 1 ${SIMULATE})
            case $FAKE_TTL in
                (+([0-9])) EXPECTED_TTL=${FAKE_TTL} ;;
            esac
        fi
        true
    else
        false
    fi
}

if [ ! -e ${VERBOSE} ]
then
    EXTRA_WRAP_ARGS+=(--quiet)
fi

if fake_update_requested
then
    # shellcheck disable=SC2086
    /usr/bin/plymouth-wrap "${EXTRA_WRAP_ARGS[@]}" ${EXPECTED_TTL} holo \
                           "Simulated Firmware Update..." \
                           "${FAKE_CMD}"
elif firmware_update_required
then
    # shellcheck disable=SC2086
    /usr/bin/plymouth-wrap "${EXTRA_WRAP_ARGS[@]}" ${EXPECTED_TTL} holo \
                           "Updating Controller Firmware" \
                           "${UPDATE_CMD}"
else
    exit 0
fi
